/**
 * What the printed map has to be true of, whatever it looks like.
 *
 * The board is generated by `scripts/generate_board.py`, which asserts its own geometry.
 * These are the facts the rest of the build reads: the engine deals a fixed number of
 * areas, the seat helpers walk `adjacency` in both directions, and every drawn district
 * has to carry the areas its capacity promises. A regenerated map that breaks one of
 * them is a bug the type checker cannot see.
 */
import { describe, expect, it } from 'vitest';

import { BOARD_ID, BOARD_VERSION, BOARD_ZONE_IDS, CORE_BOARD } from '@gerrymander/content';

describe('the board', () => {
  it('is the one the ruleset names', () => {
    expect(CORE_BOARD.id).toBe(BOARD_ID);
    expect(CORE_BOARD.version).toBe(BOARD_VERSION);
  });

  it('has every zone the schema names, once', () => {
    expect(CORE_BOARD.zones.map((zone) => zone.id)).toEqual([...BOARD_ZONE_IDS]);
  });

  it('gives each zone exactly the areas its capacity promises', () => {
    for (const zone of CORE_BOARD.zones) {
      const slots = CORE_BOARD.slots.filter((slot) => slot.zoneId === zone.id);
      expect(slots, zone.id).toHaveLength(zone.capacity);
      expect(slots.filter((slot) => slot.volatile), `${zone.id} volatile`)
        .toHaveLength(zone.volatileAreas);
    }
    expect(CORE_BOARD.slots).toHaveLength(129);
  });

  it('gives every area a unique ID and a place on the board', () => {
    const ids = new Set(CORE_BOARD.slots.map((slot) => slot.slotId));
    expect(ids.size).toBe(CORE_BOARD.slots.length);
    for (const slot of CORE_BOARD.slots) {
      expect(slot.position.x, slot.slotId).toBeGreaterThan(0);
      expect(slot.position.x, slot.slotId).toBeLessThan(1);
      expect(slot.position.y, slot.slotId).toBeGreaterThan(0);
      expect(slot.position.y, slot.slotId).toBeLessThan(1);
      expect(slot.hitRadius, slot.slotId).toBeGreaterThanOrEqual(slot.radius);
    }
  });

  it('keeps areas far enough apart that no two share a click', () => {
    const ratio = CORE_BOARD.art.aspectRatio;
    for (let i = 0; i < CORE_BOARD.slots.length; i += 1) {
      for (let j = i + 1; j < CORE_BOARD.slots.length; j += 1) {
        const left = CORE_BOARD.slots[i]!;
        const right = CORE_BOARD.slots[j]!;
        const dx = left.position.x - right.position.x;
        const dy = (left.position.y - right.position.y) * ratio;
        expect(Math.hypot(dx, dy), `${left.slotId} and ${right.slotId}`)
          .toBeGreaterThanOrEqual(left.hitRadius + right.hitRadius);
      }
    }
  });

  it('agrees with itself about who borders whom', () => {
    for (const zone of CORE_BOARD.zones) {
      expect(zone.adjacency, zone.id).not.toContain(zone.id);
      for (const neighbour of zone.adjacency) {
        const other = CORE_BOARD.zones.find((candidate) => candidate.id === neighbour)!;
        expect(other.adjacency, `${neighbour} back to ${zone.id}`).toContain(zone.id);
      }
    }
  });

  it('draws every zone as one closed outline with a plaque on it', () => {
    for (const zone of CORE_BOARD.zones) {
      expect(zone.path.startsWith('M'), zone.id).toBe(true);
      expect(zone.path.endsWith('Z'), zone.id).toBe(true);
      expect(zone.path.slice(1).includes('M'), `${zone.id} is more than one shape`).toBe(false);
      expect(zone.label.x, zone.id).toBeGreaterThan(0);
      expect(zone.label.y, zone.id).toBeLessThan(1);
    }
  });

  it('lists only moves between zones it knows', () => {
    const ids = new Set<string>(BOARD_ZONE_IDS);
    const seen = new Set<string>();
    for (const [rights, source, destination] of CORE_BOARD.movementTriples) {
      expect(ids.has(rights) && ids.has(source) && ids.has(destination)).toBe(true);
      expect(source).not.toBe(destination);
      const key = `${rights}:${source}:${destination}`;
      expect(seen.has(key), `${key} is listed twice`).toBe(false);
      seen.add(key);
    }
  });
});
