#!/usr/bin/env python3
"""Generate the typed deck modules from the JSON skeletons and card text under content/.

Run from the repository root: python3 scripts/generate_decks.py
"""
import json, os
ROOT=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC=os.path.join(ROOT,'content')
OUT=os.path.join(ROOT,'packages','content','src','campaigns','core-set')
os.makedirs(OUT, exist_ok=True)
def ts(v): return "'"+v.replace('\\','\\\\').replace("'","\\'").replace('\n','\\n')+"'"
def vec(d): return '{ '+', '.join(f'{k}: {d[k]}' for k in ('cash','influence','press','faith'))+' }'
def cost(d): return '{ '+', '.join(f'{k}: {d[k]}' for k in ('cash','influence','press','faith','generic'))+' }'
HEADER='// GENERATED by scripts/generate_decks.py from content/*.json. Edit the JSON and regenerate.\n'
# ---- policy
skel=json.load(open(SRC+'/policy-skeleton.json')); text={c['index']:c for c in json.load(open(SRC+'/policy-text.json'))}
lines=[HEADER,"import type { PolicyCard } from '../../schema.js';",'',
 '/**',' * The 108 policy cards: one question, two answers, each answer developing one archetype.',
 ' * The six archetype pairings appear 18 times each. Every answer pays 2 of its own',' * archetype\'s resource and 1 of a third; a card covers all four resources.',' */',
 'export const POLICY_CARDS: readonly PolicyCard[] = [']
for c in skel:
    t=text[c['index']]
    adv=f" advisory: '{c['advisory']}'," if c.get('advisory') else ''
    faces=[]
    for face,ans in zip(c['faces'],t['answers']):
        assert face['archetype']==ans['archetype'], c['index']
        faces.append(f"      {{ archetype: '{face['archetype']}', text: {ts(ans['text'])}, reward: {vec(face['reward'])} }},")
    lines+=[f"  {{", f"    id: '{c['id']}',{adv}", f"    question: {ts(t['question'])},", "    answers: ["]+faces+["    ],","  },"]
lines+=['];','']
open(OUT+'/policyDeck.ts','w').write('\n'.join(lines))
# ---- effects
def effects(name, const, doc):
    skel=json.load(open(f'{SRC}/{name}-skeleton.json')); text=json.load(open(f'{SRC}/{name}-text.json'))
    assert len(skel)==len(text)
    lines=[HEADER,"import type { EffectCard } from '../../schema.js';",'',f'/** {doc} */',f'export const {const}: readonly EffectCard[] = [']
    for s,t in zip(skel,text):
        assert s['id']==t['id'], (s['id'],t['id'])
        adv=f" advisory: '{s['advisory']}'," if s.get('advisory') else ''
        back=f" backCost: {cost({'cash':0,'influence':0,'press':0,'faith':0,'generic':s['backCost']})}," if s.get('backCost') is not None else ''
        lines.append(f"  {{ id: '{s['id']}', deck: '{s['deck']}', title: {ts(t['title'])}, copies: {s['copies']}, flavorText: {ts(t['flavorText'])}, rulesText: {ts(t['rulesText'])}, handlerId: '{s['handlerId']}',{adv} twoPlayerExcluded: {'true' if s['twoPlayerExcluded'] else 'false'}, markerSlots: {s['markerSlots']},{back} }},")
    lines+=['];','']
    return lines
l=effects('news','NEWS_CARDS','The 20 Breaking News cards. Four are removed in a two-player game; six carry a content advisory.')
l+=['/** Cards in the Breaking News deck. */','export const NEWS_DECK_SIZE = 20;','']
open(OUT+'/newsDeck.ts','w').write('\n'.join(l))
l=effects('tricks','TRICK_CARDS','The 20 Dirty Trick cards across 16 titles. Each copy is its own card with its own ID. `backCost` is the face-down purchase price, always generic and always 4 or 5.')
open(OUT+'/trickDeck.ts','w').write('\n'.join(l))
# ---- voters
vs=json.load(open(SRC+'/voters.json'))
lines=[HEADER,"import type { VoterCard } from '../../schema.js';",'','/**',' * The 60 voter cards. Each 1-voter card costs 3 resources, each 2-voter card 4, and',' * each 3-voter card 5.',' */','export const VOTER_CARDS: readonly VoterCard[] = [']
for v in vs: lines.append(f"  {{ id: '{v['id']}', voters: {v['voters']}, cost: {cost(v['cost'])} }},")
lines+=['];','']
open(OUT+'/voterDeck.ts','w').write('\n'.join(lines))
print('decks written to', OUT)
