"""Generate the SeatGrab grid-nine board: nine rounded-rectangle zones on a 3x3 grid, 129 areas."""
import re, math, sys
OLD=sys.argv[1]; OUT=sys.argv[2]
old=open(OLD).read()
adj=dict(re.findall(r"id: '(\w+)', displayName: '[^']+', capacity: \d+, majorityThreshold: \d+, volatileAreas: \d+, adjacency: \[([^\]]*)\]", old))
triples=re.findall(r"\['(\w+)', '(\w+)', '(\w+)'\]", old)
W,H=1000,1160
M,G=24,28
cols=[(M,290),(M+290+G,316),(M+290+G+316+G,290)]
rows=[(M,360),(M+360+G,336),(M+360+G+336+G,360)]
ZONES=[('northWest','North West',11,6,1,0,0),('north','North',21,11,2,1,0),('northEast','North East',11,6,1,2,0),
       ('west','West',17,9,1,0,1),('central','Central',9,5,1,1,1),('east','East',17,9,1,2,1),
       ('southWest','South West',11,6,1,0,2),('south','South',21,11,2,1,2),('southEast','South East',11,6,1,2,2)]
SP=48; RAD=22; HIT=30; LABEL_DY=58; SLOT_TOP=160
def rrect(x,y,w,h,r=18):
    return (f"M{x+r} {y}H{x+w-r}Q{x+w} {y} {x+w} {y+r}V{y+h-r}Q{x+w} {y+h} {x+w-r} {y+h}H{x+r}Q{x} {y+h} {x} {y+h-r}V{y+r}Q{x} {y} {x+r} {y}Z")
zone_lines=[]; slot_lines=[]
for zid,name,cap,thr,vol,ci,ri in ZONES:
    x,w=cols[ci]; y,h=rows[ri]
    colsmax=int((w-70)//SP)+1
    nrows=math.ceil(cap/colsmax); ncols=math.ceil(cap/nrows)
    # distribute counts per row as evenly as possible, larger rows first
    base,extra=divmod(cap,nrows); counts=[base+(1 if i<extra else 0) for i in range(nrows)]
    avail_h=h-SLOT_TOP-30
    assert (nrows-1)*SP<=avail_h, (zid,nrows,avail_h)
    top=y+SLOT_TOP+ (avail_h-(nrows-1)*SP)/2
    cx=x+w/2
    pts=[]
    for r_i,n in enumerate(counts):
        yy=top+r_i*SP
        span=(n-1)*SP
        for c_i in range(n):
            pts.append((cx-span/2+c_i*SP, yy))
    # volatile: nearest to the slot-area centre
    ccy=top+(nrows-1)*SP/2
    order=sorted(range(len(pts)), key=lambda i: (pts[i][0]-cx)**2+(pts[i][1]-ccy)**2)
    volatile=set(order[:vol])
    adj_s=adj[zid]
    zone_lines.append(f"    {{ id: '{zid}', displayName: '{name}', capacity: {cap}, majorityThreshold: {thr}, volatileAreas: {vol}, adjacency: [{adj_s}], label: {{ x: {cx/W:.6f}, y: {(y+LABEL_DY)/H:.6f} }}, path: '{rrect(x,y,w,h)}' }},")
    for i,(px,py) in enumerate(pts):
        slot_lines.append(f"    {{ slotId: '{zid}-{i+1:02d}', zoneId: '{zid}', position: {{ x: {px/W:.6f}, y: {py/H:.6f} }}, radius: {RAD/W:.6f}, hitRadius: {HIT/W:.6f}, volatile: {'true' if i in volatile else 'false'} }},")
assert len(slot_lines)==129, len(slot_lines)
ts=f"""// GENERATED by scripts/generate_board.py. Edit the script and regenerate; do not hand-edit.
//
// The board is an abstract 3x3 grid of rounded rectangles. Zone legality comes from
// `adjacency` and `movementTriples`, not from where the rectangles sit.

import type {{ BoardDefinition }} from '../schema.js';

/** The nine-zone, 129-area SeatGrab board. */
export const CORE_BOARD: BoardDefinition = {{
  id: 'grid-nine',
  version: '2.0.0',
  zones: [
{chr(10).join(zone_lines)}
  ],
  slots: [
{chr(10).join(slot_lines)}
  ],
  movementTriples: [
{chr(10).join(f"    ['{a}', '{b}', '{c}']," for a,b,c in triples)}
  ],
  art: {{
    aspectRatio: {H/W:.6f},
    viewBox: '0 0 {W} {H}',
  }},
}};
"""
open(OUT,'w').write(ts)
print('zones',len(zone_lines),'slots',len(slot_lines),'triples',len(triples))
