// GENERATED by scripts/generate_decks.py from content/*.json. Edit the JSON and regenerate.

import type { PolicyCard } from '../../schema.js';

/**
 * The 108 policy cards: one question, two answers, each answer developing one archetype.
 * The six archetype pairings appear 18 times each. Every answer pays 2 of its own
 * archetype's resource and 1 of a third; a card covers all four resources.
 */
export const POLICY_CARDS: readonly PolicyCard[] = [
  {
    id: 'POL001',
    question: 'Should the state scrap rent caps and let landlords charge market rates?',
    answers: [
      { archetype: 'corporate', text: 'Yes. Let supply and demand set the price, not paperwork.', reward: { cash: 2, influence: 0, press: 0, faith: 1 } },
      { archetype: 'populist', text: 'No. Nobody\'s landlord needs a bigger yacht this year.', reward: { cash: 0, influence: 1, press: 2, faith: 0 } },
    ],
  },
  {
    id: 'POL002',
    question: 'Should grocery chains be free to raise prices whenever costs rise?',
    answers: [
      { archetype: 'corporate', text: 'Yes. Margins keep the shelves stocked, so let pricing breathe.', reward: { cash: 2, influence: 1, press: 0, faith: 0 } },
      { archetype: 'populist', text: 'No. Folks are choosing between bread and the electric bill!', reward: { cash: 0, influence: 0, press: 2, faith: 1 } },
    ],
  },
  {
    id: 'POL003',
    question: 'Should gig platforms classify drivers as contractors, not employees?',
    answers: [
      { archetype: 'corporate', text: 'Yes. Flexibility beats a fixed payroll every single quarter.', reward: { cash: 2, influence: 1, press: 0, faith: 0 } },
      { archetype: 'populist', text: 'No. Call it what it is: work without a safety net.', reward: { cash: 0, influence: 0, press: 2, faith: 1 } },
    ],
  },
  {
    id: 'POL004',
    question: 'Should banks be allowed to charge fees for falling below a minimum balance?',
    answers: [
      { archetype: 'corporate', text: 'Yes. Maintaining an account costs money, so someone pays it.', reward: { cash: 2, influence: 1, press: 0, faith: 0 } },
      { archetype: 'populist', text: 'No. Broke folks shouldn\'t be fined for being broke.', reward: { cash: 0, influence: 0, press: 2, faith: 1 } },
    ],
  },
  {
    id: 'POL005',
    question: 'Should companies be free to advertise directly to children during cartoons?',
    answers: [
      { archetype: 'corporate', text: 'Yes. Kids are consumers too, and brands earned that airtime.', reward: { cash: 2, influence: 1, press: 0, faith: 0 } },
      { archetype: 'populist', text: 'No. Selling sugar dreams to toddlers is a rigged game.', reward: { cash: 0, influence: 0, press: 2, faith: 1 } },
    ],
  },
  {
    id: 'POL006',
    question: 'Should celebrities be allowed to endorse products they\'ve never used?',
    answers: [
      { archetype: 'corporate', text: 'Yes. A famous face sells faster than a spec sheet ever could.', reward: { cash: 2, influence: 1, press: 0, faith: 0 } },
      { archetype: 'populist', text: 'No. The crowd deserves better than a paid smile.', reward: { cash: 0, influence: 0, press: 2, faith: 1 } },
    ],
  },
  {
    id: 'POL007',
    question: 'Should public money fund a new stadium for a private sports team?',
    answers: [
      { archetype: 'corporate', text: 'Yes. Stadiums pull tourists, jobs, and tax revenue to town.', reward: { cash: 2, influence: 0, press: 0, faith: 1 } },
      { archetype: 'populist', text: 'No. Build us a hospital before you build them a skybox.', reward: { cash: 0, influence: 1, press: 2, faith: 0 } },
    ],
  },
  {
    id: 'POL008',
    question: 'Should schools rewrite history lessons to glorify past strongmen?',
    answers: [
      { archetype: 'populist', text: 'Yes. Teach kids winners write history, not professors.', reward: { cash: 0, influence: 1, press: 2, faith: 0 } },
      { archetype: 'reformer', text: 'No. Curricula belong to historians, not applause lines.', reward: { cash: 1, influence: 0, press: 0, faith: 2 } },
    ],
  },
  {
    id: 'POL009',
    question: 'Should businesses replace tipping with a flat built-in service charge?',
    answers: [
      { archetype: 'corporate', text: 'Yes. Predictable pricing keeps both customers and staff calm.', reward: { cash: 2, influence: 1, press: 0, faith: 0 } },
      { archetype: 'populist', text: 'No. Don\'t hide the bill and call it fairness.', reward: { cash: 0, influence: 0, press: 2, faith: 1 } },
    ],
  },
  {
    id: 'POL010',
    question: 'Should the government raise tariffs on imported manufactured goods?',
    answers: [
      { archetype: 'corporate', text: 'No. Free trade grows the pie for everyone.', reward: { cash: 2, influence: 0, press: 0, faith: 1 } },
      { archetype: 'nationalist', text: 'Yes. Protect our factories from foreign competition.', reward: { cash: 0, influence: 2, press: 1, faith: 0 } },
    ],
  },
  {
    id: 'POL011',
    question: 'Should the state increase defense spending this year?',
    answers: [
      { archetype: 'corporate', text: 'No. Efficient budgets beat bloated arsenals.', reward: { cash: 2, influence: 0, press: 1, faith: 0 } },
      { archetype: 'nationalist', text: 'Yes. A strong nation needs a stronger military.', reward: { cash: 0, influence: 2, press: 0, faith: 1 } },
    ],
  },
  {
    id: 'POL012', advisory: 'sensitive',
    question: 'Should new mining permits be granted near ancestral burial grounds?',
    answers: [
      { archetype: 'corporate', text: 'Yes. Mineral wealth benefits the whole economy.', reward: { cash: 2, influence: 0, press: 1, faith: 0 } },
      { archetype: 'nationalist', text: 'No. Our ancestors\' resting grounds deserve respect.', reward: { cash: 0, influence: 2, press: 0, faith: 1 } },
    ],
  },
  {
    id: 'POL013',
    question: 'Should the government subsidize domestic factory production?',
    answers: [
      { archetype: 'corporate', text: 'No. Let competition decide who deserves capital.', reward: { cash: 2, influence: 0, press: 0, faith: 1 } },
      { archetype: 'nationalist', text: 'Yes. Our factories keep the nation self-reliant.', reward: { cash: 0, influence: 2, press: 1, faith: 0 } },
    ],
  },
  {
    id: 'POL014',
    question: 'Should farm subsidies for domestic growers be expanded?',
    answers: [
      { archetype: 'corporate', text: 'No. Markets set fairer prices than subsidy checks.', reward: { cash: 2, influence: 0, press: 1, faith: 0 } },
      { archetype: 'nationalist', text: 'Yes. Feeding our people starts with our own soil.', reward: { cash: 0, influence: 2, press: 0, faith: 1 } },
    ],
  },
  {
    id: 'POL015',
    question: 'Should the state fund new strategic mineral refining plants?',
    answers: [
      { archetype: 'corporate', text: 'No. Importing refined minerals is simply cheaper.', reward: { cash: 2, influence: 0, press: 1, faith: 0 } },
      { archetype: 'nationalist', text: 'Yes. Refining at home secures our strategic supply.', reward: { cash: 0, influence: 2, press: 0, faith: 1 } },
    ],
  },
  {
    id: 'POL016',
    question: 'Should the government cap foreign investment in local industries?',
    answers: [
      { archetype: 'corporate', text: 'No. Foreign capital fuels growth for everyone.', reward: { cash: 2, influence: 0, press: 1, faith: 0 } },
      { archetype: 'nationalist', text: 'Yes. Keep our key industries in our own hands.', reward: { cash: 0, influence: 2, press: 0, faith: 1 } },
    ],
  },
  {
    id: 'POL017',
    question: 'Should the treasury impose an annual wealth tax on the richest households?',
    answers: [
      { archetype: 'corporate', text: 'No. Punish success and the capital simply moves elsewhere.', reward: { cash: 2, influence: 1, press: 0, faith: 0 } },
      { archetype: 'reformer', text: 'Yes. Fortunes built on shared roads owe the commons a share.', reward: { cash: 0, influence: 0, press: 1, faith: 2 } },
    ],
  },
  {
    id: 'POL018',
    question: 'Should the state guarantee free healthcare for every citizen?',
    answers: [
      { archetype: 'corporate', text: 'No. Competing providers cut costs better than one monopoly.', reward: { cash: 2, influence: 0, press: 1, faith: 0 } },
      { archetype: 'reformer', text: 'Yes. Health care is a right, not a reward for wealth.', reward: { cash: 0, influence: 1, press: 0, faith: 2 } },
    ],
  },
  {
    id: 'POL019',
    question: 'Should low-income renters receive government housing vouchers?',
    answers: [
      { archetype: 'corporate', text: 'Yes. Vouchers let the housing market do the sorting efficiently.', reward: { cash: 2, influence: 1, press: 0, faith: 0 } },
      { archetype: 'reformer', text: 'No. Subsidize landlords and the crisis just gets pricier rent.', reward: { cash: 0, influence: 0, press: 1, faith: 2 } },
    ],
  },
  {
    id: 'POL020',
    question: 'Should the retirement age rise to match longer life expectancy?',
    answers: [
      { archetype: 'corporate', text: 'Yes. Longer careers mean lower costs and stronger growth.', reward: { cash: 2, influence: 0, press: 1, faith: 0 } },
      { archetype: 'reformer', text: 'No. Raising the age punishes workers who retire in poor health.', reward: { cash: 0, influence: 1, press: 0, faith: 2 } },
    ],
  },
  {
    id: 'POL021',
    question: 'Should public universities charge students market-rate tuition?',
    answers: [
      { archetype: 'corporate', text: 'Yes. Tuition prices signal which degrees the market values.', reward: { cash: 2, influence: 0, press: 1, faith: 0 } },
      { archetype: 'reformer', text: 'No. Education should open doors, not lock them behind debt.', reward: { cash: 0, influence: 1, press: 0, faith: 2 } },
    ],
  },
  {
    id: 'POL022',
    question: 'Should industry pay a carbon price for every tonne it emits?',
    answers: [
      { archetype: 'corporate', text: 'No. A carbon price just taxes growth investors already fund.', reward: { cash: 2, influence: 0, press: 1, faith: 0 } },
      { archetype: 'reformer', text: 'Yes. Polluters should pay the true cost of the harm they cause.', reward: { cash: 0, influence: 1, press: 0, faith: 2 } },
    ],
  },
  {
    id: 'POL023',
    question: 'Should companies be barred from selling customers\' personal data?',
    answers: [
      { archetype: 'corporate', text: 'No. Data trading fuels the innovation investors are betting on.', reward: { cash: 2, influence: 1, press: 0, faith: 0 } },
      { archetype: 'reformer', text: 'Yes. Personal data belongs to the person, not the highest bidder.', reward: { cash: 0, influence: 0, press: 1, faith: 2 } },
    ],
  },
  {
    id: 'POL024',
    question: 'Should regulators break up dominant companies that crush rivals?',
    answers: [
      { archetype: 'corporate', text: 'No. Scale builds efficiency that smaller rivals can\'t match.', reward: { cash: 2, influence: 1, press: 0, faith: 0 } },
      { archetype: 'reformer', text: 'Yes. No firm should outgrow the institutions meant to check it.', reward: { cash: 0, influence: 0, press: 1, faith: 2 } },
    ],
  },
  {
    id: 'POL025',
    question: 'Should the town impose a curfew whenever tempers flare downtown?',
    answers: [
      { archetype: 'populist', text: 'No. Cage the crowd and you just hand the elite an empty stage.', reward: { cash: 0, influence: 0, press: 2, faith: 1 } },
      { archetype: 'nationalist', text: 'Yes. Quiet streets after dark keep order stronger than any speech.', reward: { cash: 1, influence: 2, press: 0, faith: 0 } },
    ],
  },
  {
    id: 'POL026', advisory: 'trigger',
    question: 'Should every officer patrolling the square wear a body camera?',
    answers: [
      { archetype: 'populist', text: 'Yes. Strap a camera on every badge, let the people watch back.', reward: { cash: 1, influence: 0, press: 2, faith: 0 } },
      { archetype: 'nationalist', text: 'No. Watching our guardians work breeds doubt, not discipline.', reward: { cash: 0, influence: 2, press: 0, faith: 1 } },
    ],
  },
  {
    id: 'POL027', advisory: 'trigger',
    question: 'Should stadiums ban traveling fans after repeated brawls on the terraces?',
    answers: [
      { archetype: 'populist', text: 'No. Ban the fans and you silence the only real roar left in town.', reward: { cash: 0, influence: 0, press: 2, faith: 1 } },
      { archetype: 'nationalist', text: 'Yes. Banners and pride are welcome; fistfights on the terraces are not.', reward: { cash: 1, influence: 2, press: 0, faith: 0 } },
    ],
  },
  {
    id: 'POL028',
    question: 'Should backyard fireworks be banned before the harvest festival?',
    answers: [
      { archetype: 'populist', text: 'Yes. Save the big bangs for the square, where the cameras roll.', reward: { cash: 0, influence: 0, press: 2, faith: 1 } },
      { archetype: 'nationalist', text: 'No. A little smoke and noise is how a proud town lets off steam.', reward: { cash: 1, influence: 2, press: 0, faith: 0 } },
    ],
  },
  {
    id: 'POL029',
    question: 'Should unlicensed street vendors be cleared from the plaza?',
    answers: [
      { archetype: 'populist', text: 'No. The vendor cart sits closer to the people than any office.', reward: { cash: 0, influence: 0, press: 2, faith: 1 } },
      { archetype: 'nationalist', text: 'Yes. A tidy plaza reflects a disciplined, well-run town.', reward: { cash: 1, influence: 2, press: 0, faith: 0 } },
    ],
  },
  {
    id: 'POL030', advisory: 'sensitive',
    question: 'Should small amounts of recreational drugs be decriminalized?',
    answers: [
      { archetype: 'populist', text: 'Yes. Stop jailing the little guy for what the rich do at private parties.', reward: { cash: 0, influence: 0, press: 2, faith: 1 } },
      { archetype: 'nationalist', text: 'No. A strong nation keeps its head clear and its laws firm.', reward: { cash: 1, influence: 2, press: 0, faith: 0 } },
    ],
  },
  {
    id: 'POL031',
    question: 'Should the town fund shelters instead of culling stray dogs?',
    answers: [
      { archetype: 'populist', text: 'Yes. Even strays deserve better than the alley the elite ignore.', reward: { cash: 0, influence: 0, press: 2, faith: 1 } },
      { archetype: 'nationalist', text: 'No. A managed street is safer than one softened by sentiment.', reward: { cash: 1, influence: 2, press: 0, faith: 0 } },
    ],
  },
  {
    id: 'POL032',
    question: 'Should personal weapon licenses require annual renewal?',
    answers: [
      { archetype: 'populist', text: 'No. More paperwork just protects bureaucrats, not the neighborhood.', reward: { cash: 0, influence: 0, press: 2, faith: 1 } },
      { archetype: 'nationalist', text: 'Yes. A disciplined citizen keeps their license current, like their duty.', reward: { cash: 1, influence: 2, press: 0, faith: 0 } },
    ],
  },
  {
    id: 'POL033',
    question: 'Should the nation add a new holiday honoring ordinary workers?',
    answers: [
      { archetype: 'populist', text: 'Yes. Give the working crowd a day, not a speech.', reward: { cash: 0, influence: 1, press: 2, faith: 0 } },
      { archetype: 'reformer', text: 'No. Fair wages matter more than one extra day off.', reward: { cash: 1, influence: 0, press: 0, faith: 2 } },
    ],
  },
  {
    id: 'POL034', advisory: 'sensitive',
    question: 'Should public schools allow students to wear religious symbols in class?',
    answers: [
      { archetype: 'populist', text: 'No. Uniforms unite a room; exceptions just divide it.', reward: { cash: 1, influence: 0, press: 2, faith: 0 } },
      { archetype: 'reformer', text: 'Yes. Faith is a right, not a rule to break.', reward: { cash: 0, influence: 1, press: 0, faith: 2 } },
    ],
  },
  {
    id: 'POL035',
    question: 'Should the state ban under-16s from social media apps?',
    answers: [
      { archetype: 'populist', text: 'Yes. Save kids from screens built to hook them.', reward: { cash: 1, influence: 0, press: 2, faith: 0 } },
      { archetype: 'reformer', text: 'No. Regulate the platforms, not the teenagers.', reward: { cash: 0, influence: 1, press: 0, faith: 2 } },
    ],
  },
  {
    id: 'POL036',
    question: 'Should comedians be free to mock sitting officials on stage?',
    answers: [
      { archetype: 'populist', text: 'Yes. Let the crowd laugh loudest at the top brass.', reward: { cash: 0, influence: 1, press: 2, faith: 0 } },
      { archetype: 'reformer', text: 'No. Satire needs a line, not a blank check.', reward: { cash: 1, influence: 0, press: 0, faith: 2 } },
    ],
  },
  {
    id: 'POL037', advisory: 'trigger',
    question: 'Should a monument linked to a deadly crackdown be torn down?',
    answers: [
      { archetype: 'populist', text: 'Yes. Take it down before the crowd does it first.', reward: { cash: 0, influence: 1, press: 2, faith: 0 } },
      { archetype: 'reformer', text: 'No. Move it to a museum with the full record.', reward: { cash: 1, influence: 0, press: 0, faith: 2 } },
    ],
  },
  {
    id: 'POL038',
    question: 'Should the national ports be sold to private operators?',
    answers: [
      { archetype: 'corporate', text: 'Yes. Private operators run ports far more efficiently.', reward: { cash: 2, influence: 0, press: 0, faith: 1 } },
      { archetype: 'nationalist', text: 'No. Selling our ports means selling our sovereignty.', reward: { cash: 0, influence: 2, press: 1, faith: 0 } },
    ],
  },
  {
    id: 'POL039',
    question: 'Should all official signage use only the national language?',
    answers: [
      { archetype: 'populist', text: 'Yes. One tongue for one nation, no exceptions.', reward: { cash: 1, influence: 0, press: 2, faith: 0 } },
      { archetype: 'reformer', text: 'No. Signs should speak to everyone who reads them.', reward: { cash: 0, influence: 1, press: 0, faith: 2 } },
    ],
  },
  {
    id: 'POL040',
    question: 'Should the public broadcaster lose its state funding?',
    answers: [
      { archetype: 'populist', text: 'Yes. Let ratings decide, not office bureaucrats.', reward: { cash: 1, influence: 0, press: 2, faith: 0 } },
      { archetype: 'reformer', text: 'No. Independent news needs a floor, not a leash.', reward: { cash: 0, influence: 1, press: 0, faith: 2 } },
    ],
  },
  {
    id: 'POL041',
    question: 'Should the city install cameras on every street corner?',
    answers: [
      { archetype: 'nationalist', text: 'Yes. Watchful eyes keep loyal citizens safe from those who mean us harm.', reward: { cash: 0, influence: 2, press: 1, faith: 0 } },
      { archetype: 'reformer', text: 'No. Constant filming turns citizens into suspects in their own homes.', reward: { cash: 1, influence: 0, press: 0, faith: 2 } },
    ],
  },
  {
    id: 'POL042',
    question: 'Should judges be appointed for life to keep courts independent?',
    answers: [
      { archetype: 'nationalist', text: 'Yes. Steady judges answer to the nation, not to fleeting political winds.', reward: { cash: 0, influence: 2, press: 1, faith: 0 } },
      { archetype: 'reformer', text: 'No. Lifetime seats shield judges from accountability the public deserves.', reward: { cash: 1, influence: 0, press: 0, faith: 2 } },
    ],
  },
  {
    id: 'POL043',
    question: 'Should the voting age drop to sixteen?',
    answers: [
      { archetype: 'nationalist', text: 'No. Citizenship\'s duties come with age and experience, not just excitement.', reward: { cash: 1, influence: 2, press: 0, faith: 0 } },
      { archetype: 'reformer', text: 'Yes. Young citizens who work and pay taxes deserve a say in their future.', reward: { cash: 0, influence: 0, press: 1, faith: 2 } },
    ],
  },
  {
    id: 'POL044',
    question: 'Should new citizens pass a strict loyalty and history test?',
    answers: [
      { archetype: 'nationalist', text: 'Yes. Earning citizenship means proving knowledge, loyalty, and shared values.', reward: { cash: 1, influence: 2, press: 0, faith: 0 } },
      { archetype: 'reformer', text: 'No. Fair tests measure paperwork skill, not character or contribution.', reward: { cash: 0, influence: 0, press: 1, faith: 2 } },
    ],
  },
  {
    id: 'POL045',
    question: 'Should every young adult serve a year in the national guard?',
    answers: [
      { archetype: 'nationalist', text: 'Yes. Shared service forges unity and readies our nation for any threat.', reward: { cash: 1, influence: 2, press: 0, faith: 0 } },
      { archetype: 'reformer', text: 'No. Forcing service on the young ignores their own life plans and rights.', reward: { cash: 0, influence: 0, press: 1, faith: 2 } },
    ],
  },
  {
    id: 'POL046',
    question: 'Should reporters be barred from publishing leaked military documents?',
    answers: [
      { archetype: 'nationalist', text: 'Yes. Some secrets protect the nation more than headlines ever could.', reward: { cash: 1, influence: 2, press: 0, faith: 0 } },
      { archetype: 'reformer', text: 'No. A free press exposing secrets keeps power honest and accountable.', reward: { cash: 0, influence: 0, press: 1, faith: 2 } },
    ],
  },
  {
    id: 'POL047',
    question: 'Should asylum seekers face indefinite detention while cases are reviewed?',
    answers: [
      { archetype: 'nationalist', text: 'Yes. Careful screening at the border protects our people and our order.', reward: { cash: 0, influence: 2, press: 1, faith: 0 } },
      { archetype: 'reformer', text: 'No. Indefinite detention punishes the desperate before any judgment is made.', reward: { cash: 1, influence: 0, press: 0, faith: 2 } },
    ],
  },
  {
    id: 'POL048',
    question: 'Should tech companies be forced to install encryption backdoors for police?',
    answers: [
      { archetype: 'nationalist', text: 'Yes. Backdoors let us stop plots before they ever reach our streets.', reward: { cash: 1, influence: 2, press: 0, faith: 0 } },
      { archetype: 'reformer', text: 'No. A backdoor for police is a backdoor for every criminal too.', reward: { cash: 0, influence: 0, press: 1, faith: 2 } },
    ],
  },
  {
    id: 'POL049', advisory: 'sensitive',
    question: 'Should the state keep running a public lottery to raise revenue?',
    answers: [
      { archetype: 'populist', text: 'Yes. Let the crowd dream big for the price of a ticket.', reward: { cash: 0, influence: 1, press: 2, faith: 0 } },
      { archetype: 'corporate', text: 'No. Gambling revenue is a lousy substitute for tax policy.', reward: { cash: 2, influence: 0, press: 0, faith: 1 } },
    ],
  },
  {
    id: 'POL050',
    question: 'Should large stores be allowed to stay open every hour of the day?',
    answers: [
      { archetype: 'corporate', text: 'Yes. More open hours simply means more chances to sell.', reward: { cash: 2, influence: 0, press: 0, faith: 1 } },
      { archetype: 'populist', text: 'No. Workers need rest more than shareholders need one more hour.', reward: { cash: 0, influence: 1, press: 2, faith: 0 } },
    ],
  },
  {
    id: 'POL051', advisory: 'sensitive',
    question: 'Should the sovereign wealth fund invest in casino resort projects?',
    answers: [
      { archetype: 'corporate', text: 'Yes. Casino resorts promise strong returns for the fund.', reward: { cash: 2, influence: 0, press: 0, faith: 1 } },
      { archetype: 'nationalist', text: 'No. Gambling dens don\'t reflect our nation\'s values.', reward: { cash: 0, influence: 2, press: 1, faith: 0 } },
    ],
  },
  {
    id: 'POL052', advisory: 'trigger',
    question: 'Should the state approve arms exports to an active war zone?',
    answers: [
      { archetype: 'corporate', text: 'Yes. Arms contracts strengthen our defense industry\'s balance sheet.', reward: { cash: 2, influence: 0, press: 0, faith: 1 } },
      { archetype: 'nationalist', text: 'No. We won\'t arm conflicts that aren\'t ours to fight.', reward: { cash: 0, influence: 2, press: 1, faith: 0 } },
    ],
  },
  {
    id: 'POL053',
    question: 'Should the minimum wage rise faster than inflation?',
    answers: [
      { archetype: 'corporate', text: 'No. Steep wage floors just price the young out of jobs.', reward: { cash: 2, influence: 0, press: 1, faith: 0 } },
      { archetype: 'reformer', text: 'Yes. A full day\'s work should always cover a full day\'s needs.', reward: { cash: 0, influence: 1, press: 0, faith: 2 } },
    ],
  },
  {
    id: 'POL054',
    question: 'Should sugary drinks carry a special public health tax?',
    answers: [
      { archetype: 'corporate', text: 'No. Let shoppers choose; the market already sells diet options.', reward: { cash: 2, influence: 0, press: 1, faith: 0 } },
      { archetype: 'reformer', text: 'Yes. A small tax now beats a lifetime of preventable illness.', reward: { cash: 0, influence: 1, press: 0, faith: 2 } },
    ],
  },
  {
    id: 'POL055', advisory: 'trigger',
    question: 'Should police be allowed to disperse rallies that run past midnight?',
    answers: [
      { archetype: 'populist', text: 'No. The square belongs to the crowd, not whoever holds the whistle.', reward: { cash: 0, influence: 0, press: 2, faith: 1 } },
      { archetype: 'nationalist', text: 'Yes. Order after midnight matters more than any chant still going.', reward: { cash: 1, influence: 2, press: 0, faith: 0 } },
    ],
  },
  {
    id: 'POL056', advisory: 'sensitive',
    question: 'Should open drinking be allowed during the street festival?',
    answers: [
      { archetype: 'populist', text: 'Yes. Let the people toast in the square, not just in private clubs.', reward: { cash: 0, influence: 0, press: 2, faith: 1 } },
      { archetype: 'nationalist', text: 'No. A proud festival stays dignified, not stumbling by sundown.', reward: { cash: 1, influence: 2, press: 0, faith: 0 } },
    ],
  },
  {
    id: 'POL057',
    question: 'Should censors get the power to ban entire films outright?',
    answers: [
      { archetype: 'populist', text: 'Yes. Ban the elite\'s propaganda reels for good.', reward: { cash: 1, influence: 0, press: 2, faith: 0 } },
      { archetype: 'reformer', text: 'No. Ratings inform viewers; bans just silence artists.', reward: { cash: 0, influence: 1, press: 0, faith: 2 } },
    ],
  },
  {
    id: 'POL058', advisory: 'sensitive',
    question: 'Should libraries pull explicit books from their teen sections?',
    answers: [
      { archetype: 'populist', text: 'Yes. Keep the shelves clean and the parents cheering.', reward: { cash: 0, influence: 1, press: 2, faith: 0 } },
      { archetype: 'reformer', text: 'No. Age labels work better than empty shelves.', reward: { cash: 1, influence: 0, press: 0, faith: 2 } },
    ],
  },
  {
    id: 'POL059',
    question: 'Should whistleblowers get full legal immunity for exposing wrongdoing?',
    answers: [
      { archetype: 'nationalist', text: 'No. Leaking secrets, even noble ones, weakens the nation\'s defenses.', reward: { cash: 0, influence: 2, press: 1, faith: 0 } },
      { archetype: 'reformer', text: 'Yes. Protecting truth-tellers keeps every institution honest and open.', reward: { cash: 1, influence: 0, press: 0, faith: 2 } },
    ],
  },
  {
    id: 'POL060',
    question: 'Should minor crimes skip juries and go straight to a judge?',
    answers: [
      { archetype: 'nationalist', text: 'Yes. Swift judges deliver order faster than slow, unpredictable juries.', reward: { cash: 0, influence: 2, press: 1, faith: 0 } },
      { archetype: 'reformer', text: 'No. A jury of peers is the fairest shield against unchecked power.', reward: { cash: 1, influence: 0, press: 0, faith: 2 } },
    ],
  },
  {
    id: 'POL061', advisory: 'sensitive',
    question: 'Should shops be allowed to sell alcohol around the clock?',
    answers: [
      { archetype: 'corporate', text: 'Yes. Round-the-clock sales are round-the-clock revenue.', reward: { cash: 2, influence: 1, press: 0, faith: 0 } },
      { archetype: 'populist', text: 'No. 3 a.m. sales help nobody but the hangover industry.', reward: { cash: 0, influence: 0, press: 2, faith: 1 } },
    ],
  },
  {
    id: 'POL062',
    question: 'Should the city keep courting more tourists even as rents climb?',
    answers: [
      { archetype: 'corporate', text: 'Yes. Visitors bring cash that locals can\'t replace alone.', reward: { cash: 2, influence: 0, press: 0, faith: 1 } },
      { archetype: 'populist', text: 'No. Our streets aren\'t a theme park for outsiders.', reward: { cash: 0, influence: 1, press: 2, faith: 0 } },
    ],
  },
  {
    id: 'POL063',
    question: 'Should factory unions gain stronger collective bargaining rights?',
    answers: [
      { archetype: 'corporate', text: 'No. Flexible labor rules keep factories competitive.', reward: { cash: 2, influence: 0, press: 0, faith: 1 } },
      { archetype: 'nationalist', text: 'Yes. Loyal workers deserve a stronger voice.', reward: { cash: 0, influence: 2, press: 1, faith: 0 } },
    ],
  },
  {
    id: 'POL064',
    question: 'Should the state expand the national rail freight network?',
    answers: [
      { archetype: 'corporate', text: 'No. Private freight haulers already move goods efficiently.', reward: { cash: 2, influence: 0, press: 0, faith: 1 } },
      { archetype: 'nationalist', text: 'Yes. A strong rail network binds the nation together.', reward: { cash: 0, influence: 2, press: 1, faith: 0 } },
    ],
  },
  {
    id: 'POL065',
    question: 'Should shipbuilding contracts be reserved for domestic yards?',
    answers: [
      { archetype: 'corporate', text: 'No. Open bidding gets taxpayers the best price.', reward: { cash: 2, influence: 0, press: 1, faith: 0 } },
      { archetype: 'nationalist', text: 'Yes. Our ships should be built by our own hands.', reward: { cash: 0, influence: 2, press: 0, faith: 1 } },
    ],
  },
  {
    id: 'POL066',
    question: 'Should large inheritances be taxed before they pass to heirs?',
    answers: [
      { archetype: 'corporate', text: 'No. Taxing inheritance just chases family capital abroad.', reward: { cash: 2, influence: 1, press: 0, faith: 0 } },
      { archetype: 'reformer', text: 'Yes. Opportunity shouldn\'t be inherited only by the lucky few.', reward: { cash: 0, influence: 0, press: 1, faith: 2 } },
    ],
  },
  {
    id: 'POL067',
    question: 'Should protest organizers need a permit filed a week in advance?',
    answers: [
      { archetype: 'populist', text: 'No. Real anger doesn\'t wait a week for a stamp from city hall.', reward: { cash: 1, influence: 0, press: 2, faith: 0 } },
      { archetype: 'nationalist', text: 'Yes. Notice and order let a rally stay peaceful and proud.', reward: { cash: 0, influence: 2, press: 0, faith: 1 } },
    ],
  },
  {
    id: 'POL068',
    question: 'Should standing for the anthem be mandatory at public events?',
    answers: [
      { archetype: 'populist', text: 'No. Loyalty forced by rule is just theater for the cameras.', reward: { cash: 0, influence: 0, press: 2, faith: 1 } },
      { archetype: 'nationalist', text: 'Yes. Standing together for the anthem is the least a nation asks.', reward: { cash: 1, influence: 2, press: 0, faith: 0 } },
    ],
  },
  {
    id: 'POL069',
    question: 'Should national museums start charging visitors an entry fee?',
    answers: [
      { archetype: 'populist', text: 'No. Culture isn\'t a toll booth for working folks.', reward: { cash: 0, influence: 1, press: 2, faith: 0 } },
      { archetype: 'reformer', text: 'Yes. Fees fund the archives future generations need.', reward: { cash: 1, influence: 0, press: 0, faith: 2 } },
    ],
  },
  {
    id: 'POL070',
    question: 'Should the city fund murals painted by local street artists?',
    answers: [
      { archetype: 'populist', text: 'Yes. Paint the walls with the people\'s own voice.', reward: { cash: 0, influence: 1, press: 2, faith: 0 } },
      { archetype: 'reformer', text: 'No. Fund studios and grants, not just blank walls.', reward: { cash: 1, influence: 0, press: 0, faith: 2 } },
    ],
  },
  {
    id: 'POL071',
    question: 'Should the leader gain emergency powers during a national crisis?',
    answers: [
      { archetype: 'nationalist', text: 'Yes. A firm hand can act fast when the nation faces real danger.', reward: { cash: 1, influence: 2, press: 0, faith: 0 } },
      { archetype: 'reformer', text: 'No. Emergency powers, once granted, rarely get handed back freely.', reward: { cash: 0, influence: 0, press: 1, faith: 2 } },
    ],
  },
  {
    id: 'POL072',
    question: 'Should every citizen carry a mandatory national ID card?',
    answers: [
      { archetype: 'nationalist', text: 'Yes. One card, one nation, one clear way to know who belongs here.', reward: { cash: 0, influence: 2, press: 1, faith: 0 } },
      { archetype: 'reformer', text: 'No. Mandatory ID cards track citizens who\'ve done nothing wrong at all.', reward: { cash: 1, influence: 0, press: 0, faith: 2 } },
    ],
  },
  {
    id: 'POL073',
    question: 'Should ride-hailing apps be free to set fares with surge pricing?',
    answers: [
      { archetype: 'corporate', text: 'Yes. Prices rise with demand, same as any honest market.', reward: { cash: 2, influence: 0, press: 0, faith: 1 } },
      { archetype: 'populist', text: 'No. Charging double in a storm is just plain greed.', reward: { cash: 0, influence: 1, press: 2, faith: 0 } },
    ],
  },
  {
    id: 'POL074',
    question: 'Should delivery apps keep charging restaurants a cut of every order?',
    answers: [
      { archetype: 'corporate', text: 'Yes. The app built the road, so it earns the toll.', reward: { cash: 2, influence: 1, press: 0, faith: 0 } },
      { archetype: 'populist', text: 'No. The little diner shouldn\'t feed a giant\'s commission.', reward: { cash: 0, influence: 0, press: 2, faith: 1 } },
    ],
  },
  {
    id: 'POL075',
    question: 'Should the government approve construction of new nuclear power plants?',
    answers: [
      { archetype: 'corporate', text: 'No. Reactors cost too much for shaky investor returns.', reward: { cash: 2, influence: 0, press: 0, faith: 1 } },
      { archetype: 'nationalist', text: 'Yes. Nuclear power frees us from foreign energy.', reward: { cash: 0, influence: 2, press: 1, faith: 0 } },
    ],
  },
  {
    id: 'POL076',
    question: 'Should the government subsidize domestic solar panel manufacturing?',
    answers: [
      { archetype: 'corporate', text: 'No. Cheaper imported panels serve consumers better.', reward: { cash: 2, influence: 0, press: 0, faith: 1 } },
      { archetype: 'nationalist', text: 'Yes. Our own panels mean energy we control.', reward: { cash: 0, influence: 2, press: 1, faith: 0 } },
    ],
  },
  {
    id: 'POL077',
    question: 'Should the water supply remain a fully public utility?',
    answers: [
      { archetype: 'corporate', text: 'No. A privatized network attracts the investment pipes need.', reward: { cash: 2, influence: 1, press: 0, faith: 0 } },
      { archetype: 'reformer', text: 'Yes. No investor should profit from a resource life depends on.', reward: { cash: 0, influence: 0, press: 1, faith: 2 } },
    ],
  },
  {
    id: 'POL078',
    question: 'Should the government subsidize childcare for working parents?',
    answers: [
      { archetype: 'corporate', text: 'Yes. Subsidized childcare grows the workforce and the economy.', reward: { cash: 2, influence: 0, press: 1, faith: 0 } },
      { archetype: 'reformer', text: 'No. Vouchers just hand public money to for-profit chains.', reward: { cash: 0, influence: 1, press: 0, faith: 2 } },
    ],
  },
  {
    id: 'POL079', advisory: 'sensitive',
    question: 'Should religious processions be rerouted away from the main square?',
    answers: [
      { archetype: 'populist', text: 'No. The square belongs to the people\'s rituals, not the planners.', reward: { cash: 0, influence: 0, press: 2, faith: 1 } },
      { archetype: 'nationalist', text: 'Yes. Old rites deserve a quieter path, not a traffic jam.', reward: { cash: 1, influence: 2, press: 0, faith: 0 } },
    ],
  },
  {
    id: 'POL080',
    question: 'Should festival crowd sizes be capped for safety?',
    answers: [
      { archetype: 'populist', text: 'No. The bigger the crowd, the louder the message to the palace.', reward: { cash: 0, influence: 0, press: 2, faith: 1 } },
      { archetype: 'nationalist', text: 'Yes. A well-ordered festival honors tradition without the crush.', reward: { cash: 1, influence: 2, press: 0, faith: 0 } },
    ],
  },
  {
    id: 'POL081',
    question: 'Should reality shows featuring politicians be pulled off air?',
    answers: [
      { archetype: 'populist', text: 'No. Let the cameras catch them being themselves.', reward: { cash: 0, influence: 1, press: 2, faith: 0 } },
      { archetype: 'reformer', text: 'Yes. Governing isn\'t a script written for ratings.', reward: { cash: 1, influence: 0, press: 0, faith: 2 } },
    ],
  },
  {
    id: 'POL082',
    question: 'Should the city enforce a strict nighttime noise curfew?',
    answers: [
      { archetype: 'populist', text: 'No. Let the people party past the elite\'s bedtime.', reward: { cash: 0, influence: 1, press: 2, faith: 0 } },
      { archetype: 'reformer', text: 'Yes. Quiet nights are a right for every worker.', reward: { cash: 1, influence: 0, press: 0, faith: 2 } },
    ],
  },
  {
    id: 'POL083',
    question: 'Should major laws require a public referendum before taking effect?',
    answers: [
      { archetype: 'nationalist', text: 'No. Elected leaders were chosen to decide, not endless public polling.', reward: { cash: 0, influence: 2, press: 1, faith: 0 } },
      { archetype: 'reformer', text: 'Yes. Letting citizens vote directly keeps power close to the people.', reward: { cash: 1, influence: 0, press: 0, faith: 2 } },
    ],
  },
  {
    id: 'POL084', advisory: 'trigger',
    question: 'Should doctors be legally required to report suspected abuse at home?',
    answers: [
      { archetype: 'nationalist', text: 'Yes. Guarding the family unit means catching abuse before it spreads.', reward: { cash: 0, influence: 2, press: 1, faith: 0 } },
      { archetype: 'reformer', text: 'No. Reporting rules can scare victims away from seeking any help.', reward: { cash: 1, influence: 0, press: 0, faith: 2 } },
    ],
  },
  {
    id: 'POL085',
    question: 'Should landlords be encouraged to offer rent-to-own housing schemes?',
    answers: [
      { archetype: 'corporate', text: 'Yes. Rent-to-own turns tenants into customers building equity.', reward: { cash: 2, influence: 1, press: 0, faith: 0 } },
      { archetype: 'reformer', text: 'No. These schemes trap renters in contracts stacked against them.', reward: { cash: 0, influence: 0, press: 1, faith: 2 } },
    ],
  },
  {
    id: 'POL086',
    question: 'Should credit card companies be free to raise interest rates at will?',
    answers: [
      { archetype: 'corporate', text: 'Yes. Risk-based pricing keeps credit available to everyone.', reward: { cash: 2, influence: 0, press: 0, faith: 1 } },
      { archetype: 'populist', text: 'No. Squeezing families for missing one payment is cruel.', reward: { cash: 0, influence: 1, press: 2, faith: 0 } },
    ],
  },
  {
    id: 'POL087',
    question: 'Should new toll roads be built along major freight corridors?',
    answers: [
      { archetype: 'corporate', text: 'Yes. Tolls attract investors to fund faster roads.', reward: { cash: 2, influence: 0, press: 1, faith: 0 } },
      { archetype: 'nationalist', text: 'No. Free roads keep our nation moving as one.', reward: { cash: 0, influence: 2, press: 0, faith: 1 } },
    ],
  },
  {
    id: 'POL088',
    question: 'Should billboards be allowed to cover entire building facades?',
    answers: [
      { archetype: 'corporate', text: 'Yes. Bigger ads mean bigger budgets for the whole block.', reward: { cash: 2, influence: 1, press: 0, faith: 0 } },
      { archetype: 'populist', text: 'No. Nobody voted to live inside somebody\'s advert.', reward: { cash: 0, influence: 0, press: 2, faith: 1 } },
    ],
  },
  {
    id: 'POL089',
    question: 'Should the government cap prices on life-saving medicines?',
    answers: [
      { archetype: 'corporate', text: 'No. Price caps starve the research pipeline of new cures.', reward: { cash: 2, influence: 1, press: 0, faith: 0 } },
      { archetype: 'reformer', text: 'Yes. No patient should ration medicine to afford next month\'s dose.', reward: { cash: 0, influence: 0, press: 1, faith: 2 } },
    ],
  },
  {
    id: 'POL090',
    question: 'Should public transit fares be subsidized to near-free levels?',
    answers: [
      { archetype: 'corporate', text: 'No. Fare-free transit is a subsidy investors never asked for.', reward: { cash: 2, influence: 1, press: 0, faith: 0 } },
      { archetype: 'reformer', text: 'Yes. Getting to work shouldn\'t depend on what a fare costs.', reward: { cash: 0, influence: 0, press: 1, faith: 2 } },
    ],
  },
  {
    id: 'POL091', advisory: 'sensitive',
    question: 'Should underground betting dens near the stadium be raided?',
    answers: [
      { archetype: 'populist', text: 'No. Raid the alley bets and the big houses still play untouched.', reward: { cash: 0, influence: 0, press: 2, faith: 1 } },
      { archetype: 'nationalist', text: 'Yes. Cleaning out the dens protects the nation\'s good name.', reward: { cash: 1, influence: 2, press: 0, faith: 0 } },
    ],
  },
  {
    id: 'POL092',
    question: 'Should the town raise its yearly immigration quota?',
    answers: [
      { archetype: 'populist', text: 'Yes. Fresh hands in the market beat empty stalls and slogans.', reward: { cash: 1, influence: 0, press: 2, faith: 0 } },
      { archetype: 'nationalist', text: 'No. Our people first, before the gates open any wider.', reward: { cash: 0, influence: 2, press: 0, faith: 1 } },
    ],
  },
  {
    id: 'POL093', advisory: 'trigger',
    question: 'Should libraries stay open as shelters during a citywide emergency?',
    answers: [
      { archetype: 'populist', text: 'Yes. Open the doors while officials still dither.', reward: { cash: 0, influence: 1, press: 2, faith: 0 } },
      { archetype: 'reformer', text: 'No. Shelters need trained staff, not just bookshelves.', reward: { cash: 1, influence: 0, press: 0, faith: 2 } },
    ],
  },
  {
    id: 'POL094', advisory: 'sensitive',
    question: 'Should games with gambling-style loot boxes carry a warning label?',
    answers: [
      { archetype: 'populist', text: 'Yes. Warn folks before the house takes their cash.', reward: { cash: 0, influence: 1, press: 2, faith: 0 } },
      { archetype: 'reformer', text: 'No. Ban the mechanic; a label alone won\'t stop it.', reward: { cash: 1, influence: 0, press: 0, faith: 2 } },
    ],
  },
  {
    id: 'POL095', advisory: 'trigger',
    question: 'Should riot police get broader powers to disperse unruly crowds?',
    answers: [
      { archetype: 'nationalist', text: 'Yes. Firm crowd control keeps order before unrest turns into chaos.', reward: { cash: 0, influence: 2, press: 1, faith: 0 } },
      { archetype: 'reformer', text: 'No. Broader force powers too often land hardest on peaceful protesters.', reward: { cash: 1, influence: 0, press: 0, faith: 2 } },
    ],
  },
  {
    id: 'POL096', advisory: 'trigger',
    question: 'Should health authorities be able to enforce quarantine by force?',
    answers: [
      { archetype: 'nationalist', text: 'Yes. Strict quarantine enforcement protects the whole nation from disease.', reward: { cash: 1, influence: 2, press: 0, faith: 0 } },
      { archetype: 'reformer', text: 'No. Forced quarantine without consent tramples basic personal freedom.', reward: { cash: 0, influence: 0, press: 1, faith: 2 } },
    ],
  },
  {
    id: 'POL097',
    question: 'Should resellers be free to mark up event tickets as high as they want?',
    answers: [
      { archetype: 'corporate', text: 'Yes. A ticket\'s worth whatever a fan will pay for it.', reward: { cash: 2, influence: 1, press: 0, faith: 0 } },
      { archetype: 'populist', text: 'No. Scalpers grab the seats before the fans get a shot.', reward: { cash: 0, influence: 0, press: 2, faith: 1 } },
    ],
  },
  {
    id: 'POL098',
    question: 'Should influencers be free to promote products without disclosing pay?',
    answers: [
      { archetype: 'corporate', text: 'Yes. Their audience, their content, their own call.', reward: { cash: 2, influence: 1, press: 0, faith: 0 } },
      { archetype: 'populist', text: 'No. Fans deserve to know when the love is rented.', reward: { cash: 0, influence: 0, press: 2, faith: 1 } },
    ],
  },
  {
    id: 'POL099',
    question: 'Should the state fund a domestic space launch industry?',
    answers: [
      { archetype: 'corporate', text: 'No. Rockets are a risky bet for shareholder returns.', reward: { cash: 2, influence: 0, press: 0, faith: 1 } },
      { archetype: 'nationalist', text: 'Yes. A flag in orbit proves our nation\'s strength.', reward: { cash: 0, influence: 2, press: 1, faith: 0 } },
    ],
  },
  {
    id: 'POL100', advisory: 'sensitive',
    question: 'Should the state subsidize the domestic alcohol export industry?',
    answers: [
      { archetype: 'corporate', text: 'Yes. Alcohol exports open lucrative new markets abroad.', reward: { cash: 2, influence: 0, press: 0, faith: 1 } },
      { archetype: 'nationalist', text: 'No. Our traditions aren\'t for sale to outsiders.', reward: { cash: 0, influence: 2, press: 1, faith: 0 } },
    ],
  },
  {
    id: 'POL101',
    question: 'Should the state forgive outstanding student loan debt?',
    answers: [
      { archetype: 'corporate', text: 'No. Blanket forgiveness rewards debt over disciplined budgeting.', reward: { cash: 2, influence: 1, press: 0, faith: 0 } },
      { archetype: 'reformer', text: 'Yes. A generation shouldn\'t start adulthood buried in debt.', reward: { cash: 0, influence: 0, press: 1, faith: 2 } },
    ],
  },
  {
    id: 'POL102',
    question: 'Should idle land be taxed at its full potential value?',
    answers: [
      { archetype: 'corporate', text: 'No. Taxing land value scares off developers who\'d build there.', reward: { cash: 2, influence: 0, press: 1, faith: 0 } },
      { archetype: 'reformer', text: 'Yes. Land shouldn\'t sit idle while families go without homes.', reward: { cash: 0, influence: 1, press: 0, faith: 2 } },
    ],
  },
  {
    id: 'POL103', advisory: 'trigger',
    question: 'Should the border wall be extended along the disputed ridge?',
    answers: [
      { archetype: 'populist', text: 'No. Walls cost a fortune while the crowd pays for bread.', reward: { cash: 0, influence: 0, press: 2, faith: 1 } },
      { archetype: 'nationalist', text: 'Yes. A firm wall on the ridge is worth more than any speech.', reward: { cash: 1, influence: 2, press: 0, faith: 0 } },
    ],
  },
  {
    id: 'POL104',
    question: 'Should the town hold a military parade on founding day?',
    answers: [
      { archetype: 'populist', text: 'Yes. Give the people a spectacle, not another closed-door meeting.', reward: { cash: 1, influence: 0, press: 2, faith: 0 } },
      { archetype: 'nationalist', text: 'No. Real pride marches quietly; parades are for show, not strength.', reward: { cash: 0, influence: 2, press: 0, faith: 1 } },
    ],
  },
  {
    id: 'POL105', advisory: 'trigger',
    question: 'Should police clear busking crowds that block a public sidewalk?',
    answers: [
      { archetype: 'populist', text: 'Yes. Clear it fast before things turn ugly for shoppers.', reward: { cash: 0, influence: 1, press: 2, faith: 0 } },
      { archetype: 'reformer', text: 'No. De-escalate first; force should be the last resort.', reward: { cash: 1, influence: 0, press: 0, faith: 2 } },
    ],
  },
  {
    id: 'POL106',
    question: 'Should citizens be fined for displaying a torn national flag?',
    answers: [
      { archetype: 'populist', text: 'No. Fine the profiteers, not a faded old flag.', reward: { cash: 0, influence: 1, press: 2, faith: 0 } },
      { archetype: 'reformer', text: 'Yes. Respect deserves clear, enforceable standards.', reward: { cash: 1, influence: 0, press: 0, faith: 2 } },
    ],
  },
  {
    id: 'POL107', advisory: 'sensitive',
    question: 'Should terminally ill patients have the right to choose assisted dying?',
    answers: [
      { archetype: 'nationalist', text: 'No. The state should defend life, not help arrange its ending.', reward: { cash: 0, influence: 2, press: 1, faith: 0 } },
      { archetype: 'reformer', text: 'Yes. A dignified choice at life\'s end respects personal liberty fully.', reward: { cash: 1, influence: 0, press: 0, faith: 2 } },
    ],
  },
  {
    id: 'POL108',
    question: 'Should campaigns face strict caps on election spending?',
    answers: [
      { archetype: 'nationalist', text: 'No. Strong campaigns need resources to defend the nation\'s interests.', reward: { cash: 0, influence: 2, press: 1, faith: 0 } },
      { archetype: 'reformer', text: 'Yes. Spending caps stop wealthy elites from buying every election outright.', reward: { cash: 1, influence: 0, press: 0, faith: 2 } },
    ],
  },
];
